### ISSUE TITLE
Record keyboard and mouse events

### ISSUE THREAD

**Issue by MarkLTZ** [JonathonReinhart/spice-record#22]
Hello @JonathonReinhart 

Is it possible to record on a separate file also keyboards and mouse events that with mp4 video file could be used in case of forensic analysis?

Best regards
Marco

**Comment by JonathonReinhart** [comment]
Hi @MarkLTZ,

No that is not currently possible. The reason is because spice-record cannot be connected to a spice server at the same time as a user interacting with the VM.

This is noted on the [README of this project](https://github.com/JonathonReinhart/spice-record#notes):

> Currently, the spice server only supports a single client connection. When another connection is opened, the current one is disconnected. Thus, this utility is limited in its usability as it cannot record a user interacting with the VM, and only an automatic ongoing process. There is however, an experimental feature to enable [multiple concurrent connections](https://www.spice-space.org/multiple-clients.html) to a single spice server.

Even if multi-client support existed, I would be surprised if the spice server echoed client A's inputs back to client B, as there is no reason (or existing mechanism) for it to do so. This would be like plugging in two mice into one computer, and expecting that when a user moves one mouse, the other mouse moves on the desk.

It sounds like you want a different tool entirely, which is some sort of recording spice proxy.

https://lazka.github.io/pgi-docs/SpiceClientGLib-2.0/classes.html
