### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Eijebong** [JonathonReinhart/spice-record#9]

**Comment by JonathonReinhart** [comment]
Hi @Eijebong, thanks for your interest in my project.

I'm interested in applying a permissive license; I usually select the MIT license unless I have to choose something else due to the libraries in use.

While Spice itself is [licensed GPL](https://www.spice-space.org/faq.html), I believe that the client libraries I'm using are [licensed LGPL](https://metadata.ftp-master.debian.org/changelogs//main/s/spice-gtk/spice-gtk_0.37-1_copyright). Thus, [as far as I can tell](https://softwareengineering.stackexchange.com/questions/141847/how-does-using-a-lgpl-gem-affect-my-mit-licensed-application) I am free to select whichever license I choose.

**Comment by Eijebong** [comment]
AFAIK yeah, you should be free to put this under MIT.

**Comment by JonathonReinhart** [comment]
Released under MIT. Thanks for opening the issue.

Please feel free to reach out with any other issues, or to let me know if you have success with this tool.
